// <auto-generated>
// Rewired Constants
// This list was generated on 3/08/2019 9:27:33 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace Controls {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int MOVE_HORIZONTAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int MOVE_VERTICAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int INTERACT = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Shoot")]
        public const int SHOOT = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Horizontal")]
        public const int LOOK_HORIZONTAL = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Vertical")]
        public const int LOOK_VERTICAL = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Reload")]
        public const int RELOAD = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Aim")]
        public const int AIM = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Sprint")]
        public const int SPRINT = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Slide")]
        public const int SLIDE = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Drop")]
        public const int DROP = 10;
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Main Player")]
        public const int MAIN_PLAYER = 0;
    }
}
